# Generated by Django 5.1.3 on 2024-11-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='name',
            new_name='sname',
        ),
    ]
