# Generated by Django 5.1.3 on 2024-11-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_rename_name_study_sname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='sname',
            field=models.CharField(max_length=30),
        ),
    ]
